config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'openai', to: 'openai#index'
  # Defines the root path route ("/")
  root "article#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController

def index
end

end

app/controllers/openai_controller.rb
class OpenaiController < ApplicationController 
  def index
    button = params[:help_me_get_started] != "" ? "help_me_get_started" : "analyse"
    service = OpenaiService.new(params[:title], params[:audience], params[:outline], params[:query], button)
    @response = service.call
    render turbo_stream: turbo_stream.update('response', partial: 'response', locals: { response: @response })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/article/index.html.erb
<div>
  <div class="pb-10">
    <h1 class="text-4xl text-center">Blompt</h1>
    <h2 class="text-center">AI Assisted Blog Writing</h2>
  </div>


<div class="row">
  <%= form_with url: openai_path, method: :get, class: "flex flex-col space-y-4" do |form| %>
    <%= form.label :title, class: "block" %>
    <%= form.text_area :title, size: "60x2", class: "block w-full rounded-lg", 
    data: { controller: 'autogrow', action: "input->autogrow#grow" },
    placeholder: "Enter the title of your blog post." %>

    <%= form.label :audience, class: "block" %>
    <%= form.text_area :audience, size: "60x2", class: "block w-full rounded-lg", 
    data: { controller: 'autogrow', action: "input->autogrow#grow" },
    placeholder: "Who is your blog post targeting? Try to be specific." %>

    <%= form.label :outline, class: "block" %>
    <%= form.text_area :outline, size: "60x5", class: "block w-full rounded-lg", 
    data: { controller: 'autogrow', action: "input->autogrow#grow" },
    placeholder: "What is your blog post about? And what are the points you want to cover? Be as descriptive as you can." %>

    <%= form.submit "Help me get started", name: "help_me_get_started", class: "mt-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>

    <%= form.label :writing_area %>
    <%= form.text_area :query, size: "60x10", class: "block w-full rounded-lg", placeholder: "Here is where the magic happens. The world needs to hear what you have to say." %>

    <%= form.submit 'Analyse', name: "analyse", class: "mt-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded cursor-pointer" %>
  <% end %>
</div>

<%= turbo_frame_tag 'response' do %>
    <div class="row mt-10">
        <h3>Response:
        </h3>
        <p><%= @response %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blompt2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex justify-center max-w-xxl">
      <%= yield %>
    </main>
  </body>
</html>

app/views/openai/_response.html.erb
<div class="row">
  <h3>Response:</h3>
  <p><%= response %></p>
</div>